### ISSUE TITLE
Version 2.0.0 breaks builds

### ISSUE THREAD

**Issue by bennyn** [pladaria/html5-websocket#2]
We have been successfully using html5-websocket v1.0.0 but the upgrade to v2.0.0 breaks our builds: https://travis-ci.org/wireapp/wire-web-api-client/builds/263607663

The main error is:
> Expected 'Hello, World!' to be 'Echo: Hello, World!'.

It comes from a test where an echo server is created:

```javascript
server = new WebSocketServer({port: WEBSOCKET_PORT});
server.on('connection', (ws) => {
  ws.on('message', (message) => server.clients.forEach((client) => client.send(`Echo: ${message}`)));
});
```

The test then checks if the echoed message from the server can be received:

```js
client.connect().then((socket) => {
  expect(socket).toBeDefined();

  socket.onmessage = (event) => {
    expect(event.data).toBe(`Echo: ${message}`);
    done();
  };

  socket.send(message);
}).catch(done.fail);
```

This doesn't seem to work anymore. Do you think it's related to your major upgrade of "ws"? https://github.com/pladaria/html5-websocket/commit/8a2899463411bf4fa1a5bed7a17ee2a9a0c19cd0

Here is our test setup:
- https://github.com/wireapp/wire-web-api-client/blob/v0.1.2/spec/WebSocketClientSpec.js#L12

**Comment by pladaria** [comment]
Hi, sorry for the delay, I'm very busy those days. 

I will investigate this issue ASAP.

**Comment by bennyn** [comment]
Hi @pladaria, thanks for getting in touch! Please let me know if there is anything I can help with. 

Our code is open source, so you can easily test the behaviour by updating `html5-websocket` (https://github.com/wireapp/wire-web-api-client/blob/v0.1.3/package.json#L17) and running `npm test`.

**Comment by pladaria** [comment]
Hi, please upgrade to v.2.0.1.

With that version I was able to pass your test suite after fixing a detail in your test.

Your echo server is actually sending two messages, one on connecting and another as echo, but you are only asserting the second.

```diff
diff --git a/package.json b/package.json
index 6715c11..636e613 100644
--- a/package.json
+++ b/package.json
@@ -14,7 +14,7 @@
     "@wireapp/store-engine": "0.0.22",
     "axios": "0.16.2",
     "cross-env": "5.0.5",
-    "html5-websocket": "1.0.0",
+    "html5-websocket": "^2.0.1",
     "reconnecting-websocket": "3.2.0",
     "tough-cookie": "2.3.2",
     "spark-md5": "3.0.0"
diff --git a/src/test/node/tcp/WebSocketClient.test.js b/src/test/node/tcp/WebSocketClient.test.js
index ce9e0e8..4020ba6 100644
--- a/src/test/node/tcp/WebSocketClient.test.js
+++ b/src/test/node/tcp/WebSocketClient.test.js
@@ -28,13 +28,6 @@ describe('WebSocketClient', () => {
     });
 
     it('connects to a WebSocket.', (done) => {
-      server.on('connection', (ws) => {
-        ws.on('message', message => {
-          server.clients.forEach(client => {
-            client.send(message);
-          });
-        });
-      });
 
       const message = 'Hello, World!';
       const accessTokenData = {
```

**Comment by pladaria** [comment]
I'm closing this issue, thanks for your feedback :)

**Comment by bennyn** [comment]
AWSM! THNX!!!! 😃

**Comment by bennyn** [comment]
@pladaria: While working with **html5-websocket** & **Reconnecting WebSocket** for some time, we realized that our reconnecting WebSocket test is still flaky (sometimes it works, sometimes it fails): https://github.com/wireapp/wire-web-api-client/issues/129

Can you see what's flaky here? https://github.com/wireapp/wire-web-api-client/blob/v0.1.11/src/test/node/spec/tcp/WebSocketClient.test.js#L58-L83
