### ISSUE TITLE
Add support for Webpack and Browserify

### ISSUE THREAD

**Issue by moshest** [pladaria/html5-websocket#3]
Please add support for browser compilation by adding a `"browser"` entry on the `package.json` file.

This file should contain:

```js
// Export native window.WebSocket on browsers
module.exports = WebSocket;
```

**Comment by pladaria** [comment]
Hi, I don't understand why is this needed.

I use this module with webpack for browser builds without any problems

**Comment by pladaria** [comment]
Ok, I see.

PR accepted, thanks!
